const allCountries = [
  'Afghanistan.gif',
  'Akrotiri.gif',
  'Albania.gif',
  'Algeria.gif',
  'American Samoa.gif',
  'Andorra.gif',
  'Angola.gif',
  'Anguilla.gif',
  'Antigua and Barbuda.gif',
  'Argentina.gif',
  'Armenia.gif',
  'Aruba.gif',
  'Ashmore and Cartier Islands.gif',
  'Australia.gif',
  'Austria.gif',
  'Azerbaijan.gif',
  'Bahamas, The.gif',
  'Bahrain.gif',
  'Bangladesh.gif',
  'Barbados.gif',
  'Belarus.gif',
  'Belgium.gif',
  'Belize.gif',
  'Benin.gif',
  'Bermuda.gif',
  'Bhutan.gif',
  'Bolivia.gif',
  'Bosnia and Herzegovina.gif',
  'Botswana.gif',
  'Bouvet Island.gif',
  'Brazil.gif',
  'British Indian Ocean Territory.gif',
  'British Virgin Islands.gif',
  'Brunei.gif',
  'Bulgaria.gif',
  'Burkina Faso.gif',
  'Burma.gif',
  'Burundi.gif',
  'Cambodia.gif',
  'Cameroon.gif',
  'Canada.gif',
  'Cape Verde.gif',
  'Cayman Islands.gif',
  'Central African Republic.gif',
  'Chad.gif',
  'Chile.gif',
  'China.gif',
  'Christmas Island.gif',
  'Clipperton Island.gif',
  'Cocos (Keeling) Islands.gif',
  'Colombia.gif',
  'Comoros.gif',
  'Congo, Democratic Republic of the.gif',
  'Congo, Republic of the.gif',
  'Cook Islands.gif',
  'Coral Sea Islands.gif',
  'Costa Rica.gif',
  "Cote d'Ivoire.gif",
  'Croatia.gif',
  'Cuba.gif',
  'Cyprus.gif',
  'Czech Republic.gif',
  'Denmark.gif',
  'Dhekelia.gif',
  'Djibouti.gif',
  'Dominica.gif',
  'Dominican Republic.gif',
  'Ecuador.gif',
  'Egypt.gif',
  'El Salvador.gif',
  'Equatorial Guinea.gif',
  'Eritrea.gif',
  'Estonia.gif',
  'Ethiopia.gif',
  'European Union.gif',
  'Falkland Islands (Islas Malvinas).gif',
  'Faroe Islands.gif',
  'Fiji.gif',
  'Finland.gif',
  'France.gif',
  'French Polynesia.gif',
  'French Southern and Antarctic Lands.gif',
  'Gabon.gif',
  'Gambia, The.gif',
  'Georgia.gif',
  'Germany.gif',
  'Ghana.gif',
  'Gibraltar.gif',
  'Greece.gif',
  'Greenland.gif',
  'Grenada.gif',
  'Guam.gif',
  'Guatemala.gif',
  'Guernsey.gif',
  'Guinea.gif',
  'Guinea-Bissau.gif',
  'Guyana.gif',
  'Haiti.gif',
  'Heard Island and McDonald Islands.gif',
  'Holy See (Vatican City).gif',
  'Honduras.gif',
  'Hong Kong.gif',
  'Hungary.gif',
  'Iceland.gif',
  'India.gif',
  'Indonesia.gif',
  'Iran.gif',
  'Iraq.gif',
  'Ireland.gif',
  'Isle of Man.gif',
  'Israel.gif',
  'Italy.gif',
  'Jamaica.gif',
  'Jan Mayen.gif',
  'Japan.gif',
  'Jersey.gif',
  'Jordan.gif',
  'Kazakhstan.gif',
  'Kenya.gif',
  'Kiribati.gif',
  'Korea, North.gif',
  'Korea, South.gif',
  'Kosovo.gif',
  'Kuwait.gif',
  'Kyrgyzstan.gif',
  'Laos.gif',
  'Latvia.gif',
  'Lebanon.gif',
  'Lesotho.gif',
  'Liberia.gif',
  'Libya.gif',
  'Liechtenstein.gif',
  'Lithuania.gif',
  'Luxembourg.gif',
  'Macau.gif',
  'Macedonia.gif',
  'Madagascar.gif',
  'Malawi.gif',
  'Malaysia.gif',
  'Maldives.gif',
  'Mali.gif',
  'Malta.gif',
  'Marshall Islands.gif',
  'Mauritania.gif',
  'Mauritius.gif',
  'Mayotte.gif',
  'Mexico.gif',
  'Micronesia, Federated States of.gif',
  'Moldova.gif',
  'Monaco.gif',
  'Mongolia.gif',
  'Montenegro.gif',
  'Montserrat.gif',
  'Morocco.gif',
  'Mozambique.gif',
  'Namibia.gif',
  'Nauru.gif',
  'Navassa Island.gif',
  'Nepal.gif',
  'Netherlands.gif',
  'Netherlands Antilles.gif',
  'New Caledonia.gif',
  'New Zealand.gif',
  'Nicaragua.gif',
  'Niger.gif',
  'Nigeria.gif',
  'Niue.gif',
  'Norfolk Island.gif',
  'Northern Mariana Islands.gif',
  'Norway.gif',
  'Oman.gif',
  'Pakistan.gif',
  'Palau.gif',
  'Panama.gif',
  'Papua New Guinea.gif',
  'Paraguay.gif',
  'Peru.gif',
  'Philippines.gif',
  'Pitcairn Islands.gif',
  'Poland.gif',
  'Portugal.gif',
  'Puerto Rico.gif',
  'Qatar.gif',
  'Romania.gif',
  'Russia.gif',
  'Rwanda.gif',
  'Saint Barthelemy.gif',
  'Saint Helena, Ascension, and Tristan da Cunha.gif',
  'Saint Kitts and Nevis.gif',
  'Saint Lucia.gif',
  'Saint Martin.gif',
  'Saint Pierre and Miquelon.gif',
  'Saint Vincent and the Grenadines.gif',
  'Samoa.gif',
  'San Marino.gif',
  'Sao Tome and Principe.gif',
  'Saudi Arabia.gif',
  'Senegal.gif',
  'Serbia.gif',
  'Seychelles.gif',
  'Sierra Leone.gif',
  'Singapore.gif',
  'Slovakia.gif',
  'Slovenia.gif',
  'Solomon Islands.gif',
  'Somalia.gif',
  'South Africa.gif',
  'South Georgia and South Sandwich Islands.gif',
  'Spain.gif',
  'Sri Lanka.gif',
  'Sudan.gif',
  'Suriname.gif',
  'Svalbard.gif',
  'Swaziland.gif',
  'Sweden.gif',
  'Switzerland.gif',
  'Syria.gif',
  'Taiwan.gif',
  'Tajikistan.gif',
  'Tanzania.gif',
  'Thailand.gif',
  'Timor-Leste.gif',
  'Togo.gif',
  'Tokelau.gif',
  'Tonga.gif',
  'Trinidad and Tobago.gif',
  'Tunisia.gif',
  'Turkey.gif',
  'Turkmenistan.gif',
  'Turks and Caicos Islands.gif',
  'Tuvalu.gif',
  'Uganda.gif',
  'Ukraine.gif',
  'United Arab Emirates.gif',
  'United Kingdom.gif',
  'United States.gif',
  'United States Pacific Island Wildlife Refuges.gif',
  'Uruguay.gif',
  'Uzbekistan.gif',
  'Vanuatu.gif',
  'Venezuela.gif',
  'Vietnam.gif',
  'Virgin Islands.gif',
  'Wake Island.gif',
  'Wallis and Futuna.gif',
  'Yemen.gif',
  'Zambia.gif',
  'Zimbabwe.gif',
];

export default allCountries;
